### ISSUE TITLE
Support i686-pc-windows-msvc

### ISSUE THREAD

**Issue by liranringel** [liranringel/ipconfig#1]
This crate cannot be compiled for i686-pc-windows-msvc until https://github.com/rust-lang-nursery/rust-bindgen/issues/541 is resolved.

**Comment by briansmith** [comment]
rust-lang-nursery/rust-bindgen#541 is fixed on nightly, so maybe this can be fixed now? It would require Nightly Rust for a while, then Nightly or Beta Rust, but that's better than the current state.

**Comment by liranringel** [comment]
The problem was the name mangling of the c function, it doesn't use the thiscall ABI, so it will work on stable too.
I just wait for the next release of bindgen :)
