### ISSUE TITLE
On get_search_list returns extra first result

### ISSUE THREAD

**Issue by glademiller** [liranringel/ipconfig#14]
get_search_list is returning 

["lan ad.x.com other.com", "lan", "ad.x.com", "other.com"]

Looking at adaptor properties the first entry doesn't appear but the other three do. The spaces in the first entry cause issues upstream in trust_dns_proto.

This is on Windows 10.

**Comment by glademiller** [comment]
This might not be an issue opening up the registry key shows the first entry as well. Is this an edge case that needs to be handled or are the Windows machines at my office misconfigured?

**Comment by liranringel** [comment]
Could you tell the value of SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\SearchList?

**Comment by glademiller** [comment]
The value was

lan ad.x.com other.com,lan,ad.x.com,other.com

So the code in the library is functioning as expected. The open question would be as the whether that is an incorrect configuration or something that needs to be handled. Looking at the search list in the network adaptor properties only shows the last 3 items. Yesterday I modified the registry to exclude the first item with no ill affects to the operating system.

**Comment by liranringel** [comment]
@glademiller it looks like a misconfiguration to me.
When I run `ipconfig.exe /all` with your value (`lan ad.x.com other.com,lan,ad.x.com,other.com`) I get 6 values (and even `lan` twice!), and on `ncpa.cpl` I see that they parse everything before the first comma as 1 (only 4 values).
I think the best thing to do is to leave the implementation the way it is.
