### ISSUE TITLE
unix support

### ISSUE THREAD

**Issue by aep** [liranringel/ipconfig#18]
Hi, 

any reason not to have unix support as well? 
Would be nice to have one cross platform crate instead of multiple

**Comment by liranringel** [comment]
I'm not sure if unix has the same network configuration concepts and data as in windows.
Perhaps some things should compile only to windows/unix.
The reason I created this crate is for windows support for trust-dns-resolver.
If there is a need for a cross platform library for fetching network configuration I will consider support unix.

**Comment by aep** [comment]
wthe crate has a reasonable abstaction layer as far as i understand. most apis should map directly to unix calls just fine, except ipconfig::Adapter:: dns_servers.  Dns settings are global on unix, not per interface. But we can fake that mapping by just returning the same for every interface.

the current alternative for unix appears to be https://github.com/bodoni/interface

**Comment by rotty** [comment]
@aep: I don't think it makes sense to add Unix support in this crate. For instance there is no `adapter_name()` vs `friendly_name() in Unix. Also, this crate might want to expose more fields in the future, some of which may be even more Windows-specific.

It might make sense to build an abstraction crate on top of `ipconfig` and a Unix-specific crate offering similar functionality, however.
