### ISSUE TITLE
Build fails on x86_64 -msvc targets because clang.dll cannot be found

### ISSUE THREAD

**Issue by briansmith** [liranringel/ipconfig#3]
I couldn't get ipconfig to build using cargo 0.23.0-nightly because it could not find clang.dll:

> thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'clang.dll\', \'libclang.dll\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', src\libcore\result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

IMO, it would be much better to add the necessary Windows API bindings to winapi and/or at least generate them once statically using bindgen, instead of running bindgen as part of build.rs. That way, people using the library wouldn't have to build all of bindgen's dependencies and they wouldn't have to run into issues like this one.

**Comment by liranringel** [comment]
I agree, it would be a good improvement.
