### ISSUE TITLE
[Question] How to know which interface is the one used?

### ISSUE THREAD

**Issue by Geobert** [liranringel/ipconfig#36]
Hi,

thank you very much for this useful crate :D  

I'm trying to get the local ip address of the computer and as I have VirtualBox installed, I have multiple interfaces.

How can I distinguish the real one from the virtual one? Both are `EthernetCsmacd`.

I'd like to create a server which as the IP address of my computer :)

**Comment by LuoZijun** [comment]
`route -n get default` ?

**Comment by Geobert** [comment]
Thank you, but I mean by using the crate's API

**Comment by liranringel** [comment]
You can check which adapter has gateways (>0).
It's already exposed in master but not in version 0.2.1, so I'll release it now for you :)
Does it help?

**Comment by Geobert** [comment]
Yeah it does thanks! Unfortunately, the project I was working on and needed that is cancelled ^^' But I will be handy to have anyway!

**Comment by laduke** [comment]
Windows uses the adapter with the lowest metric.
