### ISSUE TITLE
misaligned pointer dereference

### ISSUE THREAD

**Issue by oherrala** [liranringel/ipconfig#53]
I'm seeing this in our GitHub Actions failing. Tests worked with Rust 1.69.0 using `stable-i686-pc-windows-msvc` toolchain, but seems to fail with Rust 1.70.0 with same toolchain.

```
thread '<redacted>' panicked at 'panic in a function that cannot unwind', library\core\src\panicking.rs:126:5
thread '<redacted>' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x189f604', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1cd66030c949c28d\ipconfig-0.3.1\src\adapter.rs:293:23
```

Affected function:

https://github.com/liranringel/ipconfig/blob/f6d918f45b18194d4dd92bed8a8deaf82e9c0054/src/adapter.rs#L289-L301

**Comment by oherrala** [comment]
Rust 1.70.0 changelog has this line which might be relevant:

 * https://github.com/rust-lang/rust/pull/98112 This catches undefined behavior at runtime, and may cause existing code to fail.

**Comment by liranringel** [comment]
Thanks for the report!
I fixed it, and I will publish a new version soon.
